[theme]

# Primary accent color for interactive elements.
primaryColor="#3393f6"

# Background color for the main content area.
backgroundColor="#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#f0f2f6"

# Color used for almost all text.
textColor="#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font="monospace"








